UPDATE rules
SET
    namespace = $2,
    surface = $3,
    name = $4,
    description = $5,
    action = $6::rule_action,
    target_type = $7::rule_target,
    target_key = $8,
    item_ids = $9,
    boost_value = $10,
    max_pins = $11,
    segment_id = $12,
    priority = $13,
    enabled = $14,
    valid_from = $15,
    valid_until = $16,
    updated_at = now()
WHERE org_id = $1 AND rule_id = $17
RETURNING
    rule_id,
    org_id,
    namespace,
    surface,
    name,
    description,
    action,
    target_type,
    target_key,
    item_ids,
    boost_value,
    max_pins,
    segment_id,
    priority,
    enabled,
    valid_from,
    valid_until,
    created_at,
    updated_at;
