-- name: segment_profiles_upsert
INSERT INTO public.segment_profiles (
    org_id,
    namespace,
    profile_id,
    description,
    blend_alpha,
    blend_beta,
    blend_gamma,
    mmr_lambda,
    brand_cap,
    category_cap,
    profile_boost,
    profile_window_days,
    profile_top_n,
    half_life_days,
    co_vis_window_days,
    purchased_window_days,
    rule_exclude_events,
    exclude_event_types,
    brand_tag_prefixes,
    category_tag_prefixes,
    popularity_fanout
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17,
    COALESCE($18, '{}'::smallint[]),
    COALESCE($19, '{}'::text[]),
    COALESCE($20, '{}'::text[]),
    $21
) ON CONFLICT (org_id, namespace, profile_id)
DO UPDATE SET
    description = EXCLUDED.description,
    blend_alpha = EXCLUDED.blend_alpha,
    blend_beta = EXCLUDED.blend_beta,
    blend_gamma = EXCLUDED.blend_gamma,
    mmr_lambda = EXCLUDED.mmr_lambda,
    brand_cap = EXCLUDED.brand_cap,
    category_cap = EXCLUDED.category_cap,
    profile_boost = EXCLUDED.profile_boost,
    profile_window_days = EXCLUDED.profile_window_days,
    profile_top_n = EXCLUDED.profile_top_n,
    half_life_days = EXCLUDED.half_life_days,
    co_vis_window_days = EXCLUDED.co_vis_window_days,
    purchased_window_days = EXCLUDED.purchased_window_days,
    rule_exclude_events = EXCLUDED.rule_exclude_events,
    exclude_event_types = EXCLUDED.exclude_event_types,
    brand_tag_prefixes = EXCLUDED.brand_tag_prefixes,
    category_tag_prefixes = EXCLUDED.category_tag_prefixes,
    popularity_fanout = EXCLUDED.popularity_fanout,
    updated_at = now();
