import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/server/db/client";

export async function POST(req: NextRequest) {
  const { count = 50 } = (await req.json().catch(() => ({}))) as {
    count?: number;
  };
  const brands = ["Acme", "Globex", "Umbrella", "Stark", "Wayne"];
  const categories = ["Shoes", "Electronics", "Home", "Books", "Toys"];
  const adjectives = [
    "Advanced",
    "Bold",
    "Brilliant",
    "Chic",
    "Classic",
    "Classy",
    "Compact",
    "Crystal",
    "Deluxe",
    "Dynamic",
    "Eco-Friendly",
    "Eco",
    "Efficient",
    "Elegant",
    "Energy-Saving",
    "Exclusive",
    "Exquisite",
    "Fashionable",
    "Glow",
    "Hyper",
    "Innovative",
    "Intelligent",
    "Luxury",
    "Minimalist",
    "Modern",
    "Modular",
    "Multi-Functional",
    "NextGen",
    "Portable",
    "Powerful",
    "Premium",
    "Pro",
    "Radiant",
    "Refined",
    "Retro",
    "Robust",
    "Shiny",
    "Sleek",
    "Smart",
    "Sophisticated",
    "Sparkling",
    "State-of-the-Art",
    "Sturdy",
    "Stylish",
    "Supreme",
    "Trendy",
    "Ultimate",
    "Ultra",
    "Velvet",
    "Versatile",
    "Vivid",
    "Wireless",
  ];
  const nouns = [
    "Adapter",
    "Air Purifier",
    "Amplifier",
    "Backpack",
    "Battery Pack",
    "Board",
    "Bracelet",
    "Cable",
    "Camera Lens",
    "Camera",
    "Charger",
    "Clock",
    "Console",
    "Controller",
    "Converter",
    "Cooker",
    "Desktop",
    "Disk",
    "Dongle",
    "Drive",
    "Drone",
    "DSP",
    "Earbud",
    "Equalizer",
    "Fitness Tracker",
    "Flashlight",
    "Gaming Chair",
    "Graphics Card",
    "Headphone",
    "Holster",
    "Hub",
    "Jacket",
    "Keyboard Case",
    "Keyboard",
    "Lamp",
    "Laptop",
    "Lens",
    "Microphone",
    "MicroSD",
    "Modem",
    "Monitor",
    "Mouse",
    "Mug",
    "Network Switch",
    "Notebook",
    "Pen Tablet",
    "Pen",
    "Phone",
    "Preamp",
    "Printer",
    "Processor",
    "Projector Screen",
    "Projector",
    "Receiver",
    "Router",
    "Routerboard",
    "Scanner",
    "Server",
    "Smart Ring",
    "Smartwatch",
    "Sneaker",
    "Speaker",
    "Stabilizer",
    "Steamer",
    "Subwoofer",
    "Switch",
    "Tablet",
    "Thermostat",
    "Tripod",
    "VR Headset",
    "Watch",
    "Webcam",
  ];
  const data = Array.from({ length: count }).map((_, i) => ({
    sku: `RND-${Date.now()}-${i}`,
    name: `${adjectives[i % adjectives.length]} ${nouns[i % nouns.length]}`,
    description: "Random product",
    price: Math.round((10 + Math.random() * 190) * 100) / 100,
    currency: "USD",
    brand: brands[i % brands.length],
    category: categories[i % categories.length],
    imageUrl: "", // use local placeholder for reliability
    stockCount: Math.floor(Math.random() * 50) + 1,
    tagsCsv: categories[i % categories.length].toLowerCase(),
  }));
  await prisma.product.createMany({ data });
  return NextResponse.json({ inserted: data.length });
}
