// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/bandit/decide": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bandit"
                ],
                "summary": "Decide best policy for this request context",
                "parameters": [
                    {
                        "description": "Decision request",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.BanditDecideRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.BanditDecideResponse"
                        }
                    }
                }
            }
        },
        "/v1/bandit/policies": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bandit"
                ],
                "summary": "List all bandit policies (active and inactive)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Namespace",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.BanditPolicy"
                            }
                        }
                    }
                }
            }
        },
        "/v1/bandit/policies:upsert": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bandit"
                ],
                "summary": "Upsert bandit policies",
                "operationId": "upsertBanditPolicies",
                "parameters": [
                    {
                        "description": "Policies",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.BanditPoliciesUpsertRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/types.Ack"
                        }
                    }
                }
            }
        },
        "/v1/bandit/recommendations": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ranking"
                ],
                "summary": "Recommend with bandit-selected policy",
                "parameters": [
                    {
                        "description": "Request",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.RecommendWithBanditRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.RecommendWithBanditResponse"
                        }
                    }
                }
            }
        },
        "/v1/bandit/reward": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bandit"
                ],
                "summary": "Report binary reward for a previous decision",
                "parameters": [
                    {
                        "description": "Reward request",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.BanditRewardRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/types.Ack"
                        }
                    }
                }
            }
        },
        "/v1/event-types": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "List effective event-type config",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Namespace",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.EventTypeConfigUpsertResponse"
                            }
                        }
                    }
                }
            }
        },
        "/v1/event-types:upsert": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Upsert tenant event-type config",
                "operationId": "upsertEventTypes",
                "parameters": [
                    {
                        "description": "Event types",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.EventTypeConfigUpsertRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/types.Ack"
                        }
                    }
                }
            }
        },
        "/v1/events": {
            "get": {
                "description": "Get a paginated list of events with optional filtering by user_id, item_id, event_type, date range, etc.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data-management"
                ],
                "summary": "List events with pagination and filtering",
                "operationId": "listEvents",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Namespace",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Limit (default: 100, max: 1000)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset (default: 0)",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by user ID",
                        "name": "user_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by item ID",
                        "name": "item_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by event type",
                        "name": "event_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by creation date (ISO8601)",
                        "name": "created_after",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by creation date (ISO8601)",
                        "name": "created_before",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.APIError"
                        }
                    }
                }
            }
        },
        "/v1/events:batch": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ingestion"
                ],
                "summary": "Ingest events (batch)",
                "operationId": "batchEvents",
                "parameters": [
                    {
                        "description": "Events batch",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.EventsBatchRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/types.Ack"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.APIError"
                        }
                    }
                }
            }
        },
        "/v1/events:delete": {
            "post": {
                "description": "Delete events based on filters. If no filters provided, deletes all events in namespace.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data-management"
                ],
                "summary": "Delete events with optional filtering",
                "operationId": "deleteEvents",
                "parameters": [
                    {
                        "description": "Delete request",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.DeleteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.DeleteResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.APIError"
                        }
                    }
                }
            }
        },
        "/v1/items": {
            "get": {
                "description": "Get a paginated list of items with optional filtering by item_id, date range, etc.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data-management"
                ],
                "summary": "List items with pagination and filtering",
                "operationId": "listItems",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Namespace",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Limit (default: 100, max: 1000)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset (default: 0)",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by item ID",
                        "name": "item_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by creation date (ISO8601)",
                        "name": "created_after",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by creation date (ISO8601)",
                        "name": "created_before",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.APIError"
                        }
                    }
                }
            }
        },
        "/v1/items/{item_id}/similar": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ranking"
                ],
                "summary": "Get similar items",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Item ID",
                        "name": "item_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "default",
                        "description": "Namespace",
                        "name": "namespace",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Top-K",
                        "name": "k",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_http_types.ScoredItem"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.APIError"
                        }
                    }
                }
            }
        },
        "/v1/items:delete": {
            "post": {
                "description": "Delete items based on filters. If no filters provided, deletes all items in namespace.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data-management"
                ],
                "summary": "Delete items with optional filtering",
                "operationId": "deleteItems",
                "parameters": [
                    {
                        "description": "Delete request",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.DeleteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.DeleteResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.APIError"
                        }
                    }
                }
            }
        },
        "/v1/items:upsert": {
            "post": {
                "description": "Create or update items by opaque IDs.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ingestion"
                ],
                "summary": "Upsert items (batch)",
                "operationId": "upsertItems",
                "parameters": [
                    {
                        "description": "Items upsert",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.ItemsUpsertRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/types.Ack"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.APIError"
                        }
                    }
                }
            }
        },
        "/v1/recommendations": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ranking"
                ],
                "summary": "Get recommendations for a user",
                "parameters": [
                    {
                        "description": "Recommend request",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.RecommendRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.RecommendResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.APIError"
                        }
                    }
                }
            }
        },
        "/v1/users": {
            "get": {
                "description": "Get a paginated list of users with optional filtering by user_id, date range, etc.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data-management"
                ],
                "summary": "List users with pagination and filtering",
                "operationId": "listUsers",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Namespace",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Limit (default: 100, max: 1000)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset (default: 0)",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by user ID",
                        "name": "user_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by creation date (ISO8601)",
                        "name": "created_after",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by creation date (ISO8601)",
                        "name": "created_before",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.APIError"
                        }
                    }
                }
            }
        },
        "/v1/users:delete": {
            "post": {
                "description": "Delete users based on filters. If no filters provided, deletes all users in namespace.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data-management"
                ],
                "summary": "Delete users with optional filtering",
                "operationId": "deleteUsers",
                "parameters": [
                    {
                        "description": "Delete request",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.DeleteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.DeleteResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.APIError"
                        }
                    }
                }
            }
        },
        "/v1/users:upsert": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ingestion"
                ],
                "summary": "Upsert users (batch)",
                "operationId": "upsertUsers",
                "parameters": [
                    {
                        "description": "Users upsert",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.UsersUpsertRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/types.Ack"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.APIError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "common.APIError": {
            "type": "object",
            "properties": {
                "correlation_id": {
                    "type": "string"
                },
                "details": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_http_types.ScoredItem": {
            "type": "object",
            "properties": {
                "item_id": {
                    "type": "string",
                    "example": "i_101"
                },
                "reasons": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "score": {
                    "type": "number",
                    "example": 0.87
                }
            }
        },
        "types.Ack": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "types.BanditDecideRequest": {
            "type": "object",
            "properties": {
                "algorithm": {
                    "type": "string"
                },
                "candidate_policy_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "context": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "namespace": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "surface": {
                    "type": "string"
                }
            }
        },
        "types.BanditDecideResponse": {
            "type": "object",
            "properties": {
                "algorithm": {
                    "type": "string"
                },
                "bucket_key": {
                    "type": "string"
                },
                "explain": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "explore": {
                    "type": "boolean"
                },
                "policy_id": {
                    "type": "string"
                },
                "surface": {
                    "type": "string"
                }
            }
        },
        "types.BanditPoliciesUpsertRequest": {
            "type": "object",
            "properties": {
                "namespace": {
                    "type": "string"
                },
                "policies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.BanditPolicy"
                    }
                }
            }
        },
        "types.BanditPolicy": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "blend_alpha": {
                    "type": "number"
                },
                "blend_beta": {
                    "type": "number"
                },
                "blend_gamma": {
                    "type": "number"
                },
                "brand_cap": {
                    "type": "integer"
                },
                "category_cap": {
                    "type": "integer"
                },
                "mmr_lambda": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "policy_id": {
                    "type": "string"
                }
            }
        },
        "types.BanditRewardRequest": {
            "type": "object",
            "properties": {
                "algorithm": {
                    "type": "string"
                },
                "bucket_key": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "policy_id": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "reward": {
                    "type": "boolean"
                },
                "surface": {
                    "type": "string"
                }
            }
        },
        "types.DeleteRequest": {
            "type": "object",
            "properties": {
                "created_after": {
                    "description": "Date range filters",
                    "type": "string",
                    "example": "2025-01-01T00:00:00Z"
                },
                "created_before": {
                    "type": "string",
                    "example": "2025-12-31T23:59:59Z"
                },
                "event_type": {
                    "type": "integer",
                    "example": 0
                },
                "item_id": {
                    "type": "string",
                    "example": "i_123"
                },
                "namespace": {
                    "type": "string",
                    "example": "default"
                },
                "user_id": {
                    "description": "Optional filters - if not provided, deletes all data in namespace",
                    "type": "string",
                    "example": "u_123"
                }
            }
        },
        "types.DeleteResponse": {
            "type": "object",
            "properties": {
                "deleted_count": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "types.Event": {
            "type": "object",
            "properties": {
                "item_id": {
                    "type": "string",
                    "example": "i_123"
                },
                "meta": {},
                "source_event_id": {
                    "type": "string"
                },
                "ts": {
                    "type": "string",
                    "example": "2025-09-07T12:34:56Z"
                },
                "type": {
                    "description": "0=view,1=click,2=add,3=purchase,4=custom",
                    "type": "integer",
                    "example": 0
                },
                "user_id": {
                    "type": "string",
                    "example": "u_123"
                },
                "value": {
                    "type": "number",
                    "example": 1
                }
            }
        },
        "types.EventTypeConfig": {
            "type": "object",
            "properties": {
                "half_life_days": {
                    "type": "number"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "integer"
                },
                "weight": {
                    "type": "number"
                }
            }
        },
        "types.EventTypeConfigUpsertRequest": {
            "type": "object",
            "properties": {
                "namespace": {
                    "type": "string"
                },
                "types": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.EventTypeConfig"
                    }
                }
            }
        },
        "types.EventTypeConfigUpsertResponse": {
            "type": "object",
            "properties": {
                "half_life_days": {
                    "type": "number"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "source": {
                    "description": "\"tenant\" or \"default\"",
                    "type": "string"
                },
                "type": {
                    "type": "integer"
                },
                "weight": {
                    "type": "number"
                }
            }
        },
        "types.EventsBatchRequest": {
            "type": "object",
            "properties": {
                "events": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.Event"
                    }
                },
                "namespace": {
                    "type": "string",
                    "example": "default"
                }
            }
        },
        "types.Item": {
            "type": "object",
            "properties": {
                "available": {
                    "type": "boolean",
                    "example": true
                },
                "embedding": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "item_id": {
                    "type": "string",
                    "example": "i_123"
                },
                "price": {
                    "type": "number",
                    "example": 19.9
                },
                "props": {},
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "types.ItemsUpsertRequest": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.Item"
                    }
                },
                "namespace": {
                    "type": "string",
                    "example": "default"
                }
            }
        },
        "types.ListResponse": {
            "type": "object",
            "properties": {
                "has_more": {
                    "type": "boolean"
                },
                "items": {
                    "type": "array",
                    "items": {}
                },
                "limit": {
                    "type": "integer"
                },
                "next_offset": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "types.Overrides": {
            "type": "object",
            "properties": {
                "bandit_algo": {
                    "type": "string"
                },
                "blend_alpha": {
                    "type": "number"
                },
                "blend_beta": {
                    "type": "number"
                },
                "blend_gamma": {
                    "type": "number"
                },
                "brand_cap": {
                    "type": "integer"
                },
                "category_cap": {
                    "type": "integer"
                },
                "covis_window_days": {
                    "type": "integer"
                },
                "mmr_lambda": {
                    "type": "number"
                },
                "popularity_fanout": {
                    "type": "integer"
                },
                "popularity_halflife_days": {
                    "type": "integer"
                },
                "profile_boost": {
                    "type": "number"
                },
                "profile_top_n": {
                    "type": "integer"
                },
                "profile_window_days": {
                    "type": "integer"
                },
                "purchased_window_days": {
                    "type": "integer"
                },
                "rule_exclude_purchased": {
                    "type": "boolean"
                }
            }
        },
        "types.RecommendBlend": {
            "type": "object",
            "properties": {
                "als": {
                    "type": "number",
                    "example": 0
                },
                "cooc": {
                    "type": "number",
                    "example": 0.7
                },
                "pop": {
                    "type": "number",
                    "example": 0.3
                }
            }
        },
        "types.RecommendConstraints": {
            "type": "object",
            "properties": {
                "created_after": {
                    "description": "Optional ISO8601 timestamp; only consider events on/after this instant.",
                    "type": "string",
                    "example": "2025-06-01T00:00:00Z"
                },
                "exclude_item_ids": {
                    "description": "Exclude these item IDs from results.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "include_tags_any": {
                    "description": "Match if item.tags overlaps these (any). Empty/omitted = no tag filter.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "price_between": {
                    "description": "Optional price bounds: [min, max]. Either end may be omitted.",
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                }
            }
        },
        "types.RecommendRequest": {
            "type": "object",
            "properties": {
                "blend": {
                    "$ref": "#/definitions/types.RecommendBlend"
                },
                "constraints": {
                    "$ref": "#/definitions/types.RecommendConstraints"
                },
                "include_reasons": {
                    "type": "boolean",
                    "example": true
                },
                "k": {
                    "type": "integer",
                    "example": 20
                },
                "namespace": {
                    "type": "string",
                    "example": "default"
                },
                "overrides": {
                    "$ref": "#/definitions/types.Overrides"
                },
                "user_id": {
                    "type": "string",
                    "example": "u_123"
                }
            }
        },
        "types.RecommendResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_http_types.ScoredItem"
                    }
                },
                "model_version": {
                    "type": "string",
                    "example": "pop_2025-09-07_01"
                }
            }
        },
        "types.RecommendWithBanditRequest": {
            "type": "object",
            "properties": {
                "algorithm": {
                    "type": "string"
                },
                "blend": {
                    "$ref": "#/definitions/types.RecommendBlend"
                },
                "candidate_policy_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "constraints": {
                    "$ref": "#/definitions/types.RecommendConstraints"
                },
                "context": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "include_reasons": {
                    "type": "boolean",
                    "example": true
                },
                "k": {
                    "type": "integer",
                    "example": 20
                },
                "namespace": {
                    "type": "string",
                    "example": "default"
                },
                "overrides": {
                    "$ref": "#/definitions/types.Overrides"
                },
                "surface": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string",
                    "example": "u_123"
                }
            }
        },
        "types.RecommendWithBanditResponse": {
            "type": "object",
            "properties": {
                "algorithm": {
                    "type": "string"
                },
                "bandit_bucket": {
                    "type": "string"
                },
                "bandit_explain": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "chosen_policy_id": {
                    "type": "string"
                },
                "explore": {
                    "type": "boolean"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_http_types.ScoredItem"
                    }
                },
                "model_version": {
                    "type": "string",
                    "example": "pop_2025-09-07_01"
                }
            }
        },
        "types.User": {
            "type": "object",
            "properties": {
                "traits": {},
                "user_id": {
                    "type": "string",
                    "example": "u_123"
                }
            }
        },
        "types.UsersUpsertRequest": {
            "type": "object",
            "properties": {
                "namespace": {
                    "type": "string",
                    "example": "default"
                },
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.User"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "localhost:8000",
	BasePath:         "/",
	Schemes:          []string{"https"},
	Title:            "Recsys API",
	Description:      "Domain-agnostic recommendation service.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
