/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/foo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List foos
         * @description List foos filtered by org and namespace
         */
        get: {
            parameters: {
                query: {
                    /** @description Organization ID */
                    org_id: string;
                    /** @description Namespace */
                    namespace: string;
                    /** @description Page size */
                    limit?: number;
                    /** @description Offset */
                    offset?: number;
                    /** @description Search term */
                    search?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["types.FooListResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["types.Problem"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create foo
         * @description Create a new foo resource
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Foo payload */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["types.CreateFooDTO"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["types.FooDTO"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["types.Problem"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["types.Problem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/foo/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get foo
         * @description Fetch a foo by ID
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Foo ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["types.FooDTO"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["types.Problem"];
                    };
                };
            };
        };
        /**
         * Update foo
         * @description Update a foo by ID
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Foo ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Foo update payload */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["types.UpdateFooDTO"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["types.FooDTO"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["types.Problem"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["types.Problem"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Delete foo
         * @description Delete a foo by ID
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Foo ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["types.Problem"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "types.CreateFooDTO": {
            name: string;
            namespace: string;
            org_id: string;
        };
        "types.FooDTO": {
            /** @example 2023-01-01T00:00:00Z */
            created_at?: string;
            /** @example 01HZJ8K9M2N3P4Q5R6S7T8U9V */
            id?: string;
            /** @example my-foo */
            name?: string;
            /** @example default */
            namespace?: string;
            /** @example org-123 */
            org_id?: string;
            /** @example 2023-01-01T00:00:00Z */
            updated_at?: string;
        };
        "types.FooListResponse": {
            data?: components["schemas"]["types.FooDTO"][];
            meta?: components["schemas"]["types.ListMeta"];
        };
        "types.ListMeta": {
            count?: number;
            filters?: {
                [key: string]: string[];
            };
            limit?: number;
            offset?: number;
            search?: string;
            total?: number;
        };
        "types.Problem": {
            detail?: string;
            instance?: string;
            status?: number;
            title?: string;
            type?: string;
        };
        "types.UpdateFooDTO": {
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
