import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/server/db/client";

export async function POST(req: NextRequest) {
  const { count = 20 } = (await req.json().catch(() => ({}))) as {
    count?: number;
  };
  const firsts = [
    "Alex",
    "Avery",
    "Blake",
    "Casey",
    "Dakota",
    "Drew",
    "Elliot",
    "Emerson",
    "Emery",
    "Finley",
    "Harlow",
    "Harper",
    "Hayden",
    "Indigo",
    "Jamie",
    "Jordan",
    "Jules",
    "Kai",
    "Lennon",
    "Logan",
    "Lux",
    "Morgan",
    "Oakley",
    "Parker",
    "Peyton",
    "Phoenix",
    "Quinn",
    "Reese",
    "Remy",
    "Riley",
    "Rowan",
    "Sage",
    "Sam",
    "Sawyer",
    "Skylar",
    "Skyler",
    "Sloane",
    "Sydney",
    "Tatum",
    "Taylor",
    "Wren",
  ];
  const lasts = [
    "Adams",
    "Bailey",
    "Bell",
    "Brooks",
    "Brown",
    "Campbell",
    "Carter",
    "Collins",
    "Cook",
    "Cooper",
    "Cox",
    "Edwards",
    "Evans",
    "Garcia",
    "Gray",
    "Hall",
    "Hill",
    "Howard",
    "James",
    "Johnson",
    "Kelly",
    "King",
    "Lee",
    "Martinez",
    "Mitchell",
    "Morgan",
    "Morris",
    "Murphy",
    "Nelson",
    "Parker",
    "Perez",
    "Peterson",
    "Phillips",
    "Price",
    "Ramirez",
    "Reed",
    "Richardson",
    "Rivera",
    "Roberts",
    "Rogers",
    "Sanchez",
    "Sanders",
    "Smith",
    "Stewart",
    "Torres",
    "Turner",
    "Walker",
    "Ward",
    "Watson",
    "Young",
  ];
  await prisma.user.createMany({
    data: Array.from({ length: count }).map((_, i) => ({
      displayName: `${firsts[i % firsts.length]} ${
        lasts[(i * 7) % lasts.length]
      }`,
    })),
  });
  return NextResponse.json({ inserted: count });
}
